module.exports = {
  mySidebar: [
    'index',
    'release-notes',
    {
      type: 'category', 
      label: 'Installation',
      collapsed: true,
      items: [
        'installation/requirements',
        'installation/supported-os',
        'installation/fetch-install-file',
        'installation/preferred-installation',
        'installation/legacy-installation',
        'installation/initial-startup',
        'installation/additional-procedures',
      ], 
    },
    {
      type: 'category', 
      label: 'Configuration',
      collapsed: true,
      items: [
        'configuration/unix-lsam-configuration',
        'configuration/security-configuration-options',
        'configuration/lsam-configuration-file',
        'configuration/parameters/tcp-ip-configuration',
        {
          type: 'category',
          label: 'Parameters',
          collapsed: true,
          items: [
        'configuration/parameters/lsam-configuration-parameters',
        'configuration/parameters/logging-configuration-parameters',
        'configuration/parameters/dispatcher-configuration-parameters',
        'configuration/parameters/jors-and-smaft-parameters',
        'configuration/parameters/sma-filein-parameters',
        'configuration/parameters/trace-option-parameters',
        'configuration/parameters/sftp-parameters',
        'configuration/parameters/fad-parameters',
        'configuration/parameters/hidden-parameters',
          ],
        },
          'configuration/updating-lsam-control-script',
          'configuration/updating-smaft-control-script',
          'configuration/configuring-time-zone',
          'configuration/automatic-startup-configuration',
          'configuration/running-multiple-lsams',
          'configuration/unix-script-requirements',
          'configuration/loading-environment-variables',
          'configuration/redirecting-stdout',
          'configuration/unix-tls-security',
      ], 
    },
    {
      type: 'category', 
      label: 'Operations',
      collapsed: true,
      items: [
        'operations/operating-the-lsam',
        'operations/unix-lsam-commands',
        {
          type: 'category', 
          label: 'Utilities',
          collapsed: true,
          items: [
            'operations/utilities/utilities',
            'operations/utilities/exit-codes',
            'operations/utilities/file-check',
            'operations/utilities/genericpgm',
            'operations/utilities/get-errno',
            'operations/utilities/install-lsam',
            'operations/utilities/install-lsam-service',
            'operations/utilities/lsam-killjob',
            'operations/utilities/maintain-ofiles',
            'operations/utilities/sma-job-step',
            'operations/utilities/sma-lsam-feedback',
            'operations/utilities/sma-ppscript',
            'operations/utilities/sma-status',
            'operations/utilities/uninstall-lsam',
          ], 
        },
        'operations/components',
      ], 
    },
    {
      type: 'category', 
      label: 'File Activity Detection Daemon',
      collapsed: true,
      items: [
        'daemon/file-activity-detection-daemon',
        'daemon/features',
        'daemon/directory-structure',
        {
          type: 'category', 
          label: 'Control File',
          collapsed: true,
          items: [
            'daemon/control-file/control-file',
            'daemon/control-file/terms-and-structure',
            'daemon/control-file/variables',
            'daemon/control-file/formatting-control-file',
            'daemon/control-file/control-file-elements',
          ], 
        },
      ], 
    },
    {
      type: 'category', 
      label: 'SMA File Transfer (SMAFT)',
      collapsed: true,
      items: [
        'smaft/introduction',
        'smaft/file-compression',
        'smaft/file-encryption',
        'smaft/stream-and-record-files',
      ], 
    },
    {
      type: 'category', 
      label: 'SMA Resource Monitor',
      collapsed: true,
      items: [
        'smarm/introduction',
        {
          type: 'category', 
          label: 'Configuration File',
          collapsed: true,
          items: [
            'smarm/configuration-file/configuration-file',
            'smarm/configuration-file/config-section',
            'smarm/configuration-file/disk-section',
            'smarm/configuration-file/process-section',
            'smarm/configuration-file/user-defined-section',
          ], 
        },
        'smarm/exception-handling',
      ], 
    },
    {
      type: 'category', 
      label: 'Reference Information',
      collapsed: true,
      items: [
        {
          type: 'category', 
          label: 'Machine Messages',
          collapsed: true,
          items: [
            'reference/machine-messages/unix-lsam-messages',
            'reference/machine-messages/jobs-running-state',
            'reference/machine-messages/completed-jobs-lsam-exit-codes',
            'reference/machine-messages/unix-file-transfer-error-codes',
            'reference/machine-messages/stdout-error-codes',
            'reference/machine-messages/stderr-preprocessing',
            'reference/machine-messages/stderr-processing',
            'reference/machine-messages/jors-errors',
          ], 
        },
        {
          type: 'category', 
          label: 'System Modification and Environment Variables',
          collapsed: true,
          items: [
            'reference/system-modification/system-impact',
            'reference/system-modification/deactivating-lsam-components',
            'reference/system-modification/removing-lsam',
            'reference/system-modification/lsam-environment-variables',
          ], 
        },
        'reference/troubleshooting',
        'reference/known-issues',
        'reference/job-resource-usage-reporting',
      ], 
    },
  ],
};
